name: Build plugin

on:
  push:
    paths:
      - 'plugin/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        sparse-checkout: |
          plugin
    - name: Build plugin
      run: |
        cd plugin
        npm install
        npm run build
        npm run package
        echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: plugins/dist/*
        artifactErrorsFailBuild: true
        tag: ${{ env.PACKAGE_VERSION }}
